#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
    /config/nginx/site-confs \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx

# copy config files
cp /defaults/nginx.conf /config/nginx/nginx.conf
cp /defaults/spot.conf /config/nginx/spot.conf
cp /defaults/default /config/nginx/site-confs/default

tpl /defaults/config.js > /config/config.js
cp /config/config.js /usr/share/spot-client/dist/config/config.js
